stages:
  - deploy

deploy_to_server:
  stage: deploy
  tags:
    - Deploy-srv-isd-auto
  script:
    # 1. Синхронизируем чистый код, полностью исключая и служебный .git, и локальный venv с .env
    - sudo -u *** /usr/bin/mkdir -p /opt/mpsiem-trueconf-notification
    - sudo -u *** /usr/bin/rsync -rlptD --delete --chmod=D775,F664 --exclude='.git' --exclude='.env' --exclude='venv' ./ /opt/mpsiem-trueconf-notification/
    
    # 2. Переходим в рабочую папку и управляем окружением отдельно
    - cd /opt/mpsiem-trueconf-notification
    - if [ ! -d "venv" ]; then python3 -m venv venv; fi
    - ./venv/bin/python3 -m pip install --upgrade pip
    - ./venv/bin/python3 -m pip install -r requirements.txt
    
    # 3. Перезапускаем системную службу
    - sudo /usr/bin/systemctl restart siem-trueconf.service
  only:
    - master
